#!/usr/bin/env node
// gen_golden_log.js — regenerate golden_log.json from git history
//
// For each .png in scripts/verify/golden/:
//   - Queries git log for the most recent commit that touched the file.
//   - Preserves existing reason_tag / reason / batch fields from the current log
//     (human-curated annotations survive re-generation).
//   - Adds a bare entry for any golden not yet in the log.
//
// Usage: node tools/session/gen_golden_log.js
// Writes: scripts/verify/golden_log.json

'use strict';
const fs            = require('fs');
const path          = require('path');
const child_process = require('child_process');

const ROOT    = path.join(__dirname, '../..');
const GL_PATH = path.join(ROOT, 'scripts/verify/golden_log.json');
const GOLD_DIR = path.join(ROOT, 'scripts/verify/golden');

function git(args) {
    return child_process.execSync(`git ${args}`, { cwd: ROOT, encoding: 'utf8' }).trim();
}

// Load existing log (to preserve curated fields)
let existing = { version: 1, note: '', entries: {} };
if (fs.existsSync(GL_PATH)) {
    existing = JSON.parse(fs.readFileSync(GL_PATH, 'utf8'));
}

const files = fs.readdirSync(GOLD_DIR).filter(f => f.endsWith('.png')).sort();
const entries = {};

for (const file of files) {
    const relPath = `scripts/verify/golden/${file}`;
    let blessedDate = 'unknown';
    let commit      = 'unknown';

    try {
        const log = git(`log --follow --format="%ad|%H" --date=short -1 -- "${relPath}"`);
        if (log) {
            const [d, h] = log.split('|');
            blessedDate = d || 'unknown';
            commit      = h ? h.slice(0, 7) : 'unknown';
        }
    } catch (_) { /* file not yet tracked */ }

    const prev = existing.entries[file] || {};
    entries[file] = {
        blessed_date: blessedDate,
        commit,
        reason_tag: prev.reason_tag || 'unknown',
        reason:     prev.reason     || '',
        batch:      prev.batch      || '',
    };
}

const out = {
    version: 1,
    note: 'Generated by tools/session/gen_golden_log.js. reason_tag/reason/batch are human-curated; re-run after each bless to refresh dates.',
    entries,
};

fs.writeFileSync(GL_PATH, JSON.stringify(out, null, 2) + '\n');
console.log(`Written ${Object.keys(entries).length} entries → ${GL_PATH}`);
