#!/usr/bin/env node
// gen_item_commits.js — generate item-commits.json from git log
//
// Scans all commits reachable from HEAD for "BL-NNN" references in the subject
// line.  For each item the MOST RECENT commit that references it is recorded
// (main-session landing commit wins over sub-agent worktree commits).
//
// Usage: node tools/session/gen_item_commits.js
// Writes: docs/development/item-commits.json

'use strict';
const fs            = require('fs');
const path          = require('path');
const child_process = require('child_process');

const ROOT = path.join(__dirname, '../..');
const OUT  = path.join(ROOT, 'docs/development/item-commits.json');

function git(args) {
    return child_process.execSync(`git ${args}`, { cwd: ROOT, encoding: 'utf8' }).trim();
}

const log = git('log --format="%H|%ad|%s" --date=short');
const BL_RE = /BL-(\d+)/g;

// Map: item-id → {commit, date, message}
// First occurrence wins (log is newest-first).
const items = {};

for (const line of log.split('\n')) {
    if (!line.trim()) continue;
    const sep  = line.indexOf('|');
    const sep2 = line.indexOf('|', sep + 1);
    const hash    = line.slice(0, sep);
    const date    = line.slice(sep + 1, sep2);
    const subject = line.slice(sep2 + 1);

    let m;
    BL_RE.lastIndex = 0;
    while ((m = BL_RE.exec(subject)) !== null) {
        const id = `BL-${m[1]}`;
        if (!items[id]) {
            items[id] = { commit: hash.slice(0, 7), date, message: subject };
        }
    }
}

// Sort by item number
const sorted = Object.fromEntries(
    Object.entries(items).sort((a, b) => {
        const na = parseInt(a[0].slice(3), 10);
        const nb = parseInt(b[0].slice(3), 10);
        return na - nb;
    })
);

const out = {
    version: 1,
    note: 'Generated by tools/session/gen_item_commits.js. Re-run after each delivery commit.',
    generated: new Date().toISOString().slice(0, 10),
    items: sorted,
};

fs.writeFileSync(OUT, JSON.stringify(out, null, 2) + '\n');
console.log(`Written ${Object.keys(sorted).length} item entries → ${OUT}`);
