module.exports = [
{doc:'NATIONS', file:'docs/politics/NATIONS.md', title:'Nations', blurb:'The nation as an actor — treasury, law, and the corp↔nation channel.', qs:[
 {n:1, ids:['NR-517','BL-539','BL-540'], q:'Does the nation grant reach a rival acting politically against the player?',
  ctx:'A rival lobbying to shift a law that binds your corp — and a nation gating you out of a territory — are consequences imposed on <b>a corp a human owns</b>, by an actor you do not control. Every widening to date has been explicit and dated; BL-450 (rivals score stance) is the closest precedent, being the first <i>relational</i> action against your corp. The 2026-08-18 grant covers a <b>nation</b> acting. Reading it as covering a rival corporation would set the quiet precedent the standing rules exist to prevent.',
  blocks:'The player-facing halves of BL-539 (lobbying) and BL-540 (nation→corp stance).',
  opts:['Grant it on the same terms as BL-450 — deterministic, seeded, scored-utility, legal verbs only','Withhold it: nations may act politically, rivals may not. Lobbying is a player-only verb for now','Grant it, but gate it behind a visibility rule so a lobbied law is always attributable to whoever bought it'], rec:0},
 {n:2, ids:['NR-517','BL-539'], q:'Is a lobbying fee consumed, or does it land in the treasury?',
  ctx:'Consumed reads as influence-buying and keeps the treasury\'s inflows purely legal — levy, tariff, charter fees. Credited closes another money loop but makes lobbying a second tax, and means <b>a nation profits from being lobbied</b> — which would give BL-542\'s scorer an incentive to be corruptible.',
  opts:['Consumed — it is a cost, not a transfer (what BL-539 assumes)','Credited to the lobbied nation\'s treasury','Split — part consumed, part credited'], rec:0}]},

{doc:'RELATIONS', file:'docs/politics/RELATIONS.md', title:'Relations', blurb:'Sentiment, stance, reputation, standing — the relational layer.', qs:[
 {n:1, ids:['NR-522','BL-545'], q:'How many dimensions does sentiment carry?',
  ctx:'Your <i>sentiment is the substrate</i> ruling settled the architecture, not the count. BL-540 proposed <b>two</b> — Access (may this corp operate in our borders) and Trust (would we contract it). <code>corp_reputation</code> reads as <b>one</b>. CONCEPT.md describes a <b>single</b> value shaped by several factors. Collapsing to one makes Access and Trust inexpressible separately, which BL-540 needs; going past two is the failure mode of every multi-dimensional reputation system — dimensions stored, displayed, never read.',
  opts:['Two — Access and Trust, generalised to every grain (what BL-545 assumes)','One value plus per-consumer thresholds; Access and Trust are different cuts of the same number','Decide per grain: nation→corp carries two, corp→corp carries one'], rec:0},
 {n:2, ids:['BL-448','BL-449'], q:'What does friendship permit?',
  ctx:'Left as "a later call" when BL-448 landed on 2026-08-19, and still later. Hostility now gates three things — interdiction, battle engagement, the march queue. <b>Friendship gates exactly zero.</b> It can be offered, accepted and dissolved, and no behaviour reads it: four verbs and a UI column that change a table nothing consumes.',
  opts:['Passage through territory','A preferential price','Shared visibility under BL-068','Immunity from interdiction','Nothing — deliberately inert until BL-315 lands its consequences'], multi:true, rec:3},
 {n:3, ids:['BL-545','BL-391','BL-543'], q:'At what rate does sentiment decay?',
  ctx:'<i>Whether</i> it decays is settled — the substrate does, which is what dissolves BL-391\'s reputation deadlock. The rate is unset. It wants the treatment BL-543 gave value: an anchor, not a guess. <b>How long should a burned relationship take to heal?</b> is a question a player can answer.',
  opts:['A campaign season — fast enough that "wait" is a real move','A few years — slow enough that a betrayal is remembered','Tied to an anchor, like BL-543: expressed against something the player already understands'], rec:2, freeform:'A number, or the anchor you would express it against.'},
 {n:4, ids:['BL-450'], q:'Does a rival get to declare hostility on the player?',
  ctx:'The 2026-08-18 grant says yes and nothing has used it, so the first implementation is also the first test of whether it feels fair. Note that <code>is_hostile</code> is <b>silent by design</b> (NR-350 — a declaration is discovered on contact, never announced), which means <b>the player\'s first signal will be a lost convoy</b>.',
  opts:['Yes, silent — as designed. Discovery on contact is the mechanic','Yes, but signalled — a rival declaration surfaces to the player','No — rivals may score stance and never declare against the player'], rec:0}]},

{doc:'META', file:'docs/META_LAYER.md', title:'Meta Layer', blurb:'The predicate and effect substrate under every rule.', qs:[
 {n:1, ids:['NR-523','BL-479','BL-480'], q:'Should the effect side be one vocabulary or two?',
  ctx:'<code>modifier_set.hpp</code>\'s header says <b>one</b> — "the closed list of scalars a tech <i>or a law</i> may move, authored once and shared". The code is <b>two</b>: BL-480 landed <code>law_effect_kind</code> as its own enum and <code>law.cpp</code> never includes <code>modifier_set.hpp</code>. There is a real reason — modifier subjects move simulation scalars, a levy is a flow of money — but nothing wrote it down, and the header still misleads a future author.',
  opts:['Correct the header to describe a money-flow effect family alongside the scalar family','Grow modifier_subject with subjects a levy could be expressed as, and make law use it','Leave it, and note the divergence in META_LAYER.md only'], rec:0},
 {n:2, ids:['NR-524'], q:'What is the stopping condition for vocabulary-only subjects?',
  ctx:'Five of six modifier subjects are wired to nothing. The principle behind it appears twice in your code unnamed — <i>a shape is only proven by an instance</i> — and it justifies the first unwired entry. It does not obviously justify the fifth. An unwired instance proves a shape; five are a vocabulary waiting for consumers, which is where <code>tech_node::condition</code> was when it was a descriptive string.',
  opts:['A cap — at most N unwired at once, enforced by a harness row or backlog_lint','Each unwired subject names the backlog item that will wire it, so it is a promise not a state','Leave it — the policy is sound and the count is not yet a problem'], rec:1},
 {n:3, ids:['BL-342','BL-087'], q:'Does anything ever need OR?',
  ctx:'A flat AND-list cannot express "iron ore OR steel". That is deliberate — no nesting, no re-converging mesh, so evaluation order stays deterministic and the predicate stays legible. It is a real expressive limit, and the first quest that wants alternatives will meet it.',
  opts:['No — keep the flat list; author two rules where alternatives are needed','Yes — revisit deliberately when the first case arrives, rather than working around it','Add a narrow escape hatch now: one level of OR, never nested'], rec:0},
 {n:4, ids:['BL-270','BL-206'], q:'Should <code>condition_text</code> be the AI\'s rendering too?',
  ctx:'It exists so two UI surfaces cannot word the same predicate differently. The word interface — ACTIONS.json and the blackboard — is a <b>third</b> surface that will need to word predicates, and nothing says it uses this.',
  opts:['Yes — one rendering for every surface, the AI included','No — the agent gets a structured form, not prose','Both — structured for the agent, condition_text for anything human-readable it emits'], rec:2}]},

{doc:'LOGISTICS', file:'docs/economy/LOGISTICS.md', title:'Logistics', blurb:'The network — reach, roads, scale, throughput. The one you flagged.', qs:[
 {n:1, ids:['BL-464'], q:'What generates Logistic Points, at what rate, and what is the smallest honest first cut?',
  ctx:'Settled: a per-tick <b>rate</b>, a <b>cap not a price</b>, the <b>node half only</b>, landing with its consumer in the same batch. Unruled: the numbers, and which of the two existing consumers goes first — <code>commit_convoy</code> and <code>run_unit_upkeep</code> both already exist. Finding 4 warns that no corp is seeded a hub, so "your own nodes decide how much you may move" is fictional at the shipped generator.',
  opts:['Cities generate it — every settlement is a node, so the rate is non-fictional from turn one','Ports and hubs only — as designed, and seed corps with one so the mechanic is reachable','Nation-level: the network is public infrastructure and LP is allocated, not owned'], rec:0, freeform:'The rate, and which consumer you want first.'},
 {n:2, ids:['BL-464'], q:'Does an over-subscribed network fail, queue, or degrade?',
  ctx:'Named as open when BL-464 was filed and still open. It decides whether LP reads as <b>a wall</b> or as <b>friction</b> — and a wall is much easier to understand and much easier to resent.',
  opts:['Fail — the leg is refused outright and the player is told why','Queue — the leg waits for capacity, arriving later','Degrade — the leg goes but slower, or partially loaded'], rec:0},
 {n:3, ids:['BL-464','BL-458'], q:'Does the player see LP as a number, a lens, or only as a refusal?',
  ctx:'A refusal-only mechanic is cheap — and it is exactly how BL-458 shipped silent. The Reach lens already exists and currently shows a binary field, so a throughput lens is a small step from something built.',
  opts:['A number, on the node and in the ledger','A lens — throughput as a field over the map, extending the Reach lens','Only a refusal, with the reason named'], multi:true, rec:1},
 {n:4, ids:['BL-464','BL-202'], q:'Should a hub be buildable by a rival?',
  ctx:'Finding 5 of the rejected first cut: <code>corp_ai.cpp</code> has no port and no inland-hub build candidate, so <b>the AI would pay LP and be unable to build the generator</b>. Either the scorer gains a candidate, or LP is an asymmetric tax on rivals from the day it lands.',
  opts:['Yes — add the build candidate to the scorer before LP lands','No — hubs are nation infrastructure, and no corp builds one','Yes, but gate it: only above a size or reach threshold'], rec:0},
 {n:5, ids:['BL-538','BL-537'], q:'What does the network cost to maintain?',
  ctx:'BL-538\'s <i>logistics maintenance</i> budget line assumes a nation can pay for road upkeep. <b>Nothing decays</b>, so nothing needs paying for — the line has no sink to fill. Either roads decay, or that budget line buys something else.',
  opts:['Roads decay without maintenance — the line has a real sink','Roads are permanent; the line buys new road instead of upkeep','Both — a low decay floor plus expansion'], rec:2}]},

{doc:'PROVINCES', file:'docs/generation/PROVINCES.md', title:'Provinces', blurb:'The spatial unit of consequence.', qs:[
 {n:1, ids:['NR-433','BL-515'], q:'Is 12% below the hard 3-tile floor acceptable?',
  ctx:'Open since 2026-08-21 and unruled. It is <b>the one measured property of the partition nobody has accepted or rejected.</b> Your own ruling was "don\'t reject tiny provinces" and nothing is merged away to satisfy a floor — so this may already be the answer.',
  opts:['Accept it — tiny provinces are the ruling working as intended','Reduce it — adjust seeding so fewer fall below three tiles','Absorb them — merge sub-floor provinces into their cheapest neighbour'], rec:0},
 {n:2, ids:['NR-421','NR-509','BL-513'], q:'What is the province building ceiling FOR, if geology already binds four times harder?',
  ctx:'Measured on the first frame it rendered: capacity <b>103</b> against <b>24</b> placement slots the province\'s own geology could ever support. The binding constraint on building is deposits, not the ceiling — <b>so the ceiling currently changes nothing.</b>',
  opts:['Drop it to where it bites','Keep it as a backstop against a future where deposits stop binding — and document that','Remove it — an inert constraint is worse than none'], rec:1},
 {n:3, ids:['BL-518'], q:'Does a province ever gain an owner?',
  ctx:'Every downstream use so far is spatial, and the restraint <i>is</i> the design — no name, no owner, no culture, no economy. The moment a province is <b>held</b> — by conquest, by charter, by garrison — it stops being anonymous and becomes the region this design explicitly refused. <b>BL-518 (war redraws borders) is where that pressure first arrives</b>, and it is design-owed.',
  opts:['No — provinces stay anonymous; ownership stays on tiles','Yes — a province gains a controller, and that is what war moves','Partially — a province has a controller for military purposes only, never an economy'], rec:2},
 {n:4, ids:['BL-516','BL-188'], q:'Do sea provinces get a naval model, or stay addressable empty space?',
  ctx:'They were built as the latter, deliberately — "addressable empty space, built without inventing the naval model that will eventually fill them". Nothing says which they become. BL-188 (coastal ports) is parked and holds the five-times speed gap between caravan and coastal vessel.',
  opts:['Stay empty — sea provinces are addressing, not gameplay','A naval model eventually — ships, blockade, coastal trade','Coastal trade only — ports and sea routes, no naval combat'], rec:2}]},

{doc:'CONTRACTS', file:'docs/economy/CONTRACTS.md', title:'Contracts', blurb:'The income loop — the reopened critical path.', qs:[
 {n:1, ids:['BL-377','BL-537'], q:'Does a contract fee come out of the national budget line, or is it minted?',
  ctx:'NATIONS.md settles that <b>actor-to-actor transfers conserve exactly</b>. A contract fee is such a transfer — so <b>a nation that cannot afford a contract must not be able to offer it.</b> That couples offer generation to BL-537\'s budget and is not stated anywhere yet.',
  opts:['From the budget — a nation cannot offer what it cannot pay, and offers dry up when treasuries do','Minted — offers are independent of the treasury, and the conservation rule has a stated exception','From the budget, with a reserve: a nation may commit up to a fraction of its treasury'], rec:0},
 {n:2, ids:['BL-377','BL-107'], q:'Inline predicate, or template index?',
  ctx:'The <code>condition_set</code> in a contract record is the one novel serialisation question — a structured predicate, not a scalar. <b>Template index recommended</b>: it keeps the record fixed-size, makes contract kinds data, and a save outliving a template change rejects rather than reinterprets.',
  opts:['Template index — an index into an authored table, predicate stays in Lua','Inline — store the predicate in the record','Defer until BL-107 gives saves a real seam'], rec:0},
 {n:3, ids:['BL-446','BL-377'], q:'Should a rival company take contracts too?',
  ctx:'If not, the player is the only mercenary in a world of polities that need one — and BL-446\'s <i>shipped and unexercised</i> defect repeats. Procurement already has this problem: no human and no AI uses it.',
  opts:['Yes — rivals compete for the same contracts, and losing a bid is a real outcome','No — the player is the protagonist mercenary; rivals stay economic','Yes, but later — after the player loop is proven'], rec:0},
 {n:4, ids:['BL-445','BL-377'], q:'What does a contract look like on screen?',
  ctx:'Procurement\'s answer is <b>nothing at all</b> — every verb is seam-only, and that is what BL-445 exists to fix. The sell side should not repeat it. Io has a comms dock, a nav rail and a fold-out ledger column already.',
  opts:['A ledger — offers, active contracts, terminal states, in the fold-out column','A comms channel — offers arrive as messages from a named client','On the map — the objective province is marked, and the contract hangs off it'], multi:true, rec:0}]},

{doc:'PEOPLE', file:'docs/PEOPLE.md', title:'People', blurb:'NEW · Named individuals holding roles. Proposal, not settled design.', qs:[
 {n:1, ids:['BL-547','BL-370','BL-207'], q:'Which roles, and in what order?',
  ctx:'Five proposed, each mapped to shipped machinery. <b>Company head (BL-370)</b> is your own earlier ask and needs no other system. <b>Minister</b> is the highest value — it gives BL-539\'s lobbying a target — but it depends on BL-537\'s budget landing. <b>Counsel (BL-207)</b> is already fully designed and parked.',
  opts:['Company head — the player\'s own figure','Counsel — advisors seated per corp (BL-207)','Commander — attached to a unit, filling the all-zero doctrine stub','Minister — holds a nation\'s budget weights','Contact — the named counterparty in a procurement pair'], multi:true, rec:0, freeform:'The order you want them in.'},
 {n:2, ids:['BL-547'], q:'One bias, or several?',
  ctx:'The proposal says <b>one</b>, on the grounds that a person with five modifiers is a spreadsheet with a name and a person with one is a character. <b>This is the call most likely to be overturned and the cheapest to change now.</b>',
  opts:['One — a person is a character, not a stat block','Two or three — a small sheet, enough for a build choice','Several — people are a real optimisation axis'], rec:0},
 {n:3, ids:['BL-547','BL-548'], q:'Are people mortal?',
  ctx:'Tenure is what makes a person more than a label — one who never leaves is a permanent modifier wearing a name. Succession would give the game <b>change the player did not cause and cannot prevent</b>, and it is the cleanest first event. It is also the thing that could make a good run feel arbitrarily punished.',
  opts:['Yes — people age and are replaced, deterministically','No — a person lasts the campaign','Only some — the player\'s own figure is permanent, others turn over'], rec:0},
 {n:4, ids:['BL-370'], q:'Does the player\'s own figure carry a bias at all?',
  ctx:'A bias on your own head is <b>a build choice</b>; no bias is <b>a portrait</b>. BL-370 asks for a named figure so the player feels a personal connection, and does not say which.',
  opts:['A bias — your figure is part of your build','No bias — pure attachment and identity','Chosen at start — the player picks their figure, and the bias with it'], rec:2},
 {n:5, ids:['BL-068','BL-547'], q:'Is a person visible to rivals?',
  ctx:'Everything else about a competitor is banded under BL-068\'s competitor-visibility rule. <b>A named opposing commander is intelligence; an anonymous one is a number.</b>',
  opts:['Visible — names are public, the bias is not','Banded like everything else — you learn who they are as you learn the rest','Hidden — a rival\'s people are private'], rec:0},
 {n:6, ids:['BL-271','BL-208'], q:'Do people exist in the pre-history?',
  ctx:'The Era −1 sim runs 4,000 years of polities. Named figures there would be <b>lore rather than mechanics</b> — and <code>history_log</code> already records deeds with no one to attribute them to.',
  opts:['Yes — the history log names who did what, as lore','No — the pre-history stays institutional','A few — only the figures whose deeds the campaign world still remembers'], rec:2}]},

{doc:'EVENTS', file:'docs/EVENTS.md', title:'Events', blurb:'NEW · Things that happen to the player. Proposal, not settled design.', qs:[
 {n:1, ids:['BL-548'], q:'Which family first?',
  ctx:'<b>Environmental</b> is cheapest — it reads generated state and lands on <code>extraction_rate</code>, the one wired modifier subject. <b>Political</b> is most valuable, because BL-537, BL-539 and BL-541 are already producing dateable changes with no notification layer — and <b>that half is arguably not "random" at all.</b>',
  opts:['Environmental — bad season, flood, a seam running thin','Economic — glut, shortage, a supplier failing','Political — a law enacted, a tariff raised, a grudge remembered','Personal — succession, death, defection (depends on PEOPLE)'], rec:2},
 {n:2, ids:['BL-548'], q:'How often is an event?',
  ctx:'<b>The single number that decides whether this reads as texture or as chaos.</b> A campaign targets ~100 hours; nothing has established a rhythm. An economy tick is one quarter, so four ticks is a year.',
  opts:['Rare — a few per campaign, each memorable','Seasonal — one every few years, so a decade has a shape','Frequent — several a year, as ambient texture'], rec:1, freeform:'A rate, if you have one in mind.'},
 {n:3, ids:['BL-548','BL-087'], q:'Does the player ever choose a response?',
  ctx:'A notification is cheap and passive. <b>A choice is a different genre</b> — and it is the point at which events become <b>quests</b>, which BL-087 owns and which is parked.',
  opts:['No — an event is a notification and a consequence','Yes — an event offers a bounded choice with priced outcomes','Some do — most are notifications; a few are decisions'], rec:0},
 {n:4, ids:['BL-477','BL-479'], q:'Do events drive the collapse metagame, or merely express it?',
  ctx:'<b>This is the question that decides how large this system is.</b> BL-477 is design-owed and says "each era has a collapse state to avoid — and that\'s what defines meta". If strain accumulates <i>from</i> events, this system is the metagame\'s engine. If events only report strain, something else accumulates it.',
  opts:['Drive it — events accumulate collapse_strain, and the metagame is made of them','Express it — strain accumulates elsewhere; events are how the player learns about it','Both — some events add strain, most report it'], rec:1},
 {n:5, ids:['BL-548'], q:'Are events symmetric?',
  ctx:'Do rivals and nations suffer them too? <b>Symmetric is fairer and much harder to balance; asymmetric is a difficulty dial pointed at the player.</b>',
  opts:['Symmetric — everyone is subject, and watching a rival get hit is content','Asymmetric — events target the player only','Symmetric for nations, player-and-rivals for corps'], rec:0},
 {n:6, ids:['BL-289'], q:'Does BL-289 (sky events as extinction drivers) come off the shelf?',
  ctx:'You deferred it in 2026-08-04 as "just flavor". Its own reasoning is the strongest case for events in the repo: <i>a supernova is the first cause that is NOT about the world — it arrives from outside, it is nobody\'s fault, and it is the only mechanism that could make two otherwise-identical worlds diverge.</i> A general event system is what would make it cheap.',
  opts:['Yes — once the event system exists, this is its most interesting instance','No — it stays deferred; the ancient arc has no telescope','Keep it generation-side only, as a pre-history divergence'], rec:2}]},

{doc:'CHAIN', file:'docs/SYSTEMS.md', title:'The Chain', blurb:'Your interconnectivity ask, written as a design test. Two claims are mine.', qs:[
 {n:1, ids:['NR-530','BL-464','BL-325'], q:'Does the chain close rather than end?',
  ctx:'My claim: force\'s ceiling is <b>supply</b>, which is the logistics rung again at a higher grain — which is BL-325 ruling 3 (<i>economic reach IS military reach</i>) read as progression rather than architecture. <b>If that is right, BL-464 is a much bigger item than its size suggests</b>, because it is the rung the whole chain plateaus at.',
  opts:['Yes — the chain closes, and logistics is the recurring constraint','No — territory is a real end state, and the chain terminates there','Partly — it closes for force, not for the economy'], rec:0},
 {n:2, ids:['NR-530','BL-548'], q:'Is "a staircase is a solved sequence" the right argument for events?',
  ctx:'My claim: a chain of systems each unlocked by the last is learned once and then followed, so <b>an event is what makes the same rung feel different on a second campaign</b> — which a ~100-hour target across many campaigns needs. The counter-argument is that a legible sequence is a feature, and unpredictability undermines the mastery a strategy game sells.',
  opts:['Right — variance is what keeps the chain worth replaying','Wrong — a learnable sequence is the point; variance belongs in world generation, not in play','Right, but bounded — variance in texture, never in the sequence itself'], rec:2}]},

{doc:'CROSS', file:'various', title:'Cross-cutting', blurb:'Four calls that span documents.', qs:[
 {n:1, ids:['NR-516'], q:'Confirm or rename the v0.1.24 minor',
  ctx:'The six corp↔nation channel items were filed at <b>v0.1.24</b> — the next free minor, since v0.1.23 is "Who owns whom" (the syndicate tier). The minor is unnamed and does not appear in ROADMAP. Naming a minor is yours.',
  opts:['Confirm v0.1.24 and name it','Fold the cluster into an existing minor','Split it — the budget and lobbying halves are separate minors'], rec:0, freeform:'A name for the minor, if you are confirming it.'},
 {n:2, ids:['NR-511'], q:'COLLAPSE.md is named as authority by 19 open items and declares itself not authority',
  ctx:'It opens "research scaffolding — the design conversation\'s home, not authority", and nineteen open backlog items point at it. A reader following the pointer lands on a page telling them it settles nothing. Five sibling scaffolding docs carry the same banner and total 3,076 lines; <b>none of the six has ever graduated.</b>',
  opts:['Graduate COLLAPSE.md to authority and drop its banner','Re-home the 19 items onto HISTORY.md and leave COLLAPSE as scaffolding','Leave it — the pointer means "read this for context"'], rec:0},
 {n:3, ids:['NR-518'], q:'Io has two clocks and "tick" means both',
  ctx:'A <b>day tick</b> is one in-game day (the survey system counts these). An <b>economy tick</b> is 90 of them — one quarter. Both readings in the corpus are correct about different clocks, so this is not a defect. It is a naming collision that has already produced two apparently contradictory statements, and GLOSSARY.md defines neither term.',
  opts:['Add both terms to GLOSSARY.md and leave the code alone','Rename one in code — econ_tick vs day_tick — so the ambiguity cannot be read','Leave it; the comments are individually correct'], rec:0},
 {n:4, ids:['NR-514','BL-480'], q:'Status drift runs both ways — should the check become a tool?',
  ctx:'BL-377 was a false <i>complete</i>. BL-480 is the opposite and confirmed: its merge is an ancestor of HEAD, the code and harness both exist, and its item still reads "designed". A first-pass sweep returns 48 candidates but is noisy with forward references, so that is an upper bound, not a count. A reliable check is cheap: an item is landed if its named files carry its id <b>and</b> a commit whose <i>subject</i> names it is an ancestor of HEAD.',
  opts:['Build the check into backlog_lint, so drift is caught at close rather than found by accident','Reconcile all 48 by hand once, and fix the statuses','Fix BL-480 only, and leave the sweep'], rec:0}]}
];
