-- Mock tech / quest tree (BL-087, design session 2026-07-08).
--
-- DATA ONLY — the tech system is post-prototype (BL-087 resolution 6); nothing in
-- the simulation reads this file. It exists so the F9 read-only viewer can show
-- the tree while the design is fresh: the fully-worked Propellant Loop quest plus
-- stub quests for the rest of the Era 0/1 map and the three standing lines.
--
-- Schema (mirrors the itemisation schema in docs/research/ERA1_TECH_LANDSCAPE.md):
--   quest: id, name, era, type ("gate"|"standing"), thread, thesis, capstone,
--          opens (quest ids the capstone unlocks — capstones open QUEST TREES,
--          not Eras, per the 2026-07-08 Era reframe), status
--   tech:  id, name, quest, kind ("invention"|"tier"|"capstone"), tier,
--          prereqs (tech ids; MAY cross quests, sparingly), cost (S/M/L/XL,
--          default M), payoff (gate|resource|building|recipe|efficiency|enabling),
--          condition (research|structure|stockpile|market|surplus|era), unlocks,
--          status
--
-- Shape rules applied (2026-07-08 resolutions): mostly a binary tree with
-- dead-end leaves (tier chains); cross-quest prereqs sparing and deliberate
-- (E1-PL-18 -> Automation line, E1-PL-21 -> Orbital Port); economic conditions
-- reserved for capstones + marquee nodes.

tech_tree = {
    quests = {
        -- ---------------------------------------------------------------- Era 0
        { id = "E0-HEAVY", name = "Heavy Industry", era = 0, type = "gate",
          thread = "Industry",
          thesis = "A steel / chemicals / refining base broad enough to build rockets from.",
          capstone = "E0-HI-04", opens = { "E0-ROCKET" }, status = "stub" },

        { id = "E0-ELEC", name = "Electronics & Computing", era = 0, type = "gate",
          thread = "Compute",
          thesis = "Info-Age footing; compute is the input the R&D Lab consumes.",
          capstone = "E0-EC-04", opens = {}, status = "stub" },

        { id = "E0-ROCKET", name = "Rocketry", era = 0, type = "gate",
          thread = "Launch",
          thesis = "An operable launch complex — the condition set ERAS.md records, re-read as a quest-tree gate.",
          capstone = "E0-RK-05",
          opens = { "E1-LAUNCH", "E1-PROPLOOP", "E1-ORBITAL" }, status = "stub" },

        -- ---------------------------------------------------------------- Era 1
        { id = "E1-LAUNCH", name = "Launch & Access", era = 1, type = "gate",
          thread = "Launch",
          thesis = "Cheap, reusable lift — the rival that undercuts ISRU below the distance/scale line.",
          capstone = "E1-LA-04", opens = {}, status = "stub" },

        { id = "E1-PROPLOOP", name = "The Propellant Loop", era = 1, type = "gate",
          thread = "ISRU",
          thesis = "Close the propellant loop off-world: find it, dig it, split it, store it, sell it.",
          capstone = "E1-PL-23", opens = {}, status = "sketch" },

        { id = "E1-ORBITAL", name = "Orbital Industry", era = 1, type = "gate",
          thread = "Orbital Construction",
          thesis = "Assembly Plant + Orbital Port: build in orbit what is too heavy to lift.",
          capstone = "E1-OR-04", opens = {}, status = "stub" },

        -- --------------------------------------------------------- Standing lines
        { id = "L-LOG", name = "Logistics", era = 0, type = "standing",
          thread = "Propulsion",
          thesis = "The convoy propellant tax, deepened forever: chemical, ion, nuclear-thermal (parked).",
          capstone = "", opens = {}, status = "stub" },

        { id = "L-AUTO", name = "Economy & Automation", era = 0, type = "standing",
          thread = "Power & Automation",
          thesis = "The workforce-scalar and power substrate behind every quest.",
          capstone = "", opens = {}, status = "stub" },

        { id = "L-MIL", name = "Military", era = 0, type = "standing",
          thread = "",
          thesis = "Reserved — not enumerated until the combat system is mapped.",
          capstone = "", opens = {}, status = "reserved" },
    },

    techs = {
        -- ------------------------------------------------- E0-HEAVY (stub, 4)
        { id = "E0-HI-01", name = "Blast-Furnace Steel", quest = "E0-HEAVY",
          kind = "invention", prereqs = {}, cost = "M", payoff = "building",
          condition = "research", unlocks = "Steel Mill", status = "stub" },
        { id = "E0-HI-02", name = "Industrial Chemistry", quest = "E0-HEAVY",
          kind = "invention", prereqs = { "E0-HI-01" }, cost = "M", payoff = "recipe",
          condition = "research", unlocks = "Petroleum -> refined fuel chains", status = "stub" },
        { id = "E0-HI-03", name = "Blast-Furnace Steel II", quest = "E0-HEAVY",
          kind = "tier", tier = 2, prereqs = { "E0-HI-01" }, cost = "S", payoff = "efficiency",
          condition = "research", unlocks = "Steel yield up", status = "stub" },
        { id = "E0-HI-04", name = "Integrated Supply Chains", quest = "E0-HEAVY",
          kind = "capstone", prereqs = { "E0-HI-02" }, cost = "XL", payoff = "gate",
          condition = "surplus", unlocks = "Quest goal: sustained steel + fuel surplus feeds Rocketry", status = "stub" },

        -- -------------------------------------------------- E0-ELEC (stub, 4)
        { id = "E0-EC-01", name = "Semiconductor Fabrication", quest = "E0-ELEC",
          kind = "invention", prereqs = {}, cost = "M", payoff = "building",
          condition = "research", unlocks = "Semiconductor Fab", status = "stub" },
        { id = "E0-EC-02", name = "Compute Clusters", quest = "E0-ELEC",
          kind = "invention", prereqs = { "E0-EC-01" }, cost = "M", payoff = "recipe",
          condition = "research", unlocks = "Compute — the R&D Lab input good", status = "stub" },
        { id = "E0-EC-03", name = "Semiconductor Fabrication II", quest = "E0-ELEC",
          kind = "tier", tier = 2, prereqs = { "E0-EC-01" }, cost = "S", payoff = "efficiency",
          condition = "research", unlocks = "Fab yield up", status = "stub" },
        { id = "E0-EC-04", name = "Information Economy", quest = "E0-ELEC",
          kind = "capstone", prereqs = { "E0-EC-02" }, cost = "XL", payoff = "gate",
          condition = "market", unlocks = "Quest goal: compute cheap enough to industrialise research", status = "stub" },

        -- ------------------------------------------------ E0-ROCKET (stub, 5)
        { id = "E0-RK-01", name = "Guided Rocketry", quest = "E0-ROCKET",
          kind = "invention", prereqs = {}, cost = "M", payoff = "enabling",
          condition = "research", unlocks = "Rocket airframes and guidance", status = "stub" },
        { id = "E0-RK-02", name = "Orbital-Class Boosters", quest = "E0-ROCKET",
          kind = "invention", prereqs = { "E0-RK-01" }, cost = "L", payoff = "building",
          condition = "research", unlocks = "Launchpad", status = "stub" },
        { id = "E0-RK-03", name = "Cryogenic Ground Handling", quest = "E0-ROCKET",
          kind = "invention", prereqs = { "E0-RK-01" }, cost = "M", payoff = "recipe",
          condition = "research", unlocks = "Propellant production and storage on the pad", status = "stub" },
        { id = "E0-RK-04", name = "Orbital-Class Boosters II", quest = "E0-ROCKET",
          kind = "tier", tier = 2, prereqs = { "E0-RK-02" }, cost = "S", payoff = "efficiency",
          condition = "research", unlocks = "Payload per launch up", status = "stub" },
        { id = "E0-RK-05", name = "Operable Launch Complex", quest = "E0-ROCKET",
          kind = "capstone", prereqs = { "E0-RK-02", "E0-RK-03" }, cost = "XL", payoff = "gate",
          condition = "structure", unlocks = "Quest goal: staffed Launchpad + propellant stockpile; opens the Era 1 quest trees", status = "stub" },

        -- ------------------------------------------------ E1-LAUNCH (stub, 4)
        { id = "E1-LA-01", name = "Reusable First Stage", quest = "E1-LAUNCH",
          kind = "invention", prereqs = { "E0-RK-05" }, cost = "L", payoff = "efficiency",
          condition = "research", unlocks = "Launch cost per kg down", status = "stub" },
        { id = "E1-LA-02", name = "Rapid Turnaround", quest = "E1-LAUNCH",
          kind = "tier", tier = 2, prereqs = { "E1-LA-01" }, cost = "S", payoff = "efficiency",
          condition = "research", unlocks = "Launch cadence up", status = "stub" },
        { id = "E1-LA-03", name = "Heavy Lift", quest = "E1-LAUNCH",
          kind = "invention", prereqs = { "E1-LA-01" }, cost = "M", payoff = "building",
          condition = "research", unlocks = "Heavy Launchpad", status = "stub" },
        { id = "E1-LA-04", name = "Routine Access", quest = "E1-LAUNCH",
          kind = "capstone", prereqs = { "E1-LA-03" }, cost = "XL", payoff = "gate",
          condition = "market", unlocks = "Quest goal: launch cheap enough that lift stops being the bottleneck", status = "stub" },

        -- ------------------------- E1-PROPLOOP (worked, ~25 — the keystone quest)
        { id = "E1-PL-01", name = "Volatile Prospecting", quest = "E1-PROPLOOP",
          kind = "invention", prereqs = {}, cost = "M", payoff = "resource",
          condition = "research", unlocks = "Ice/water richness bands appear in survey", status = "sketch" },
        { id = "E1-PL-02", name = "Volatile Prospecting II", quest = "E1-PROPLOOP",
          kind = "tier", tier = 2, prereqs = { "E1-PL-01" }, cost = "S", payoff = "efficiency",
          condition = "research", unlocks = "Survey range/accuracy up", status = "sketch" },
        { id = "E1-PL-03", name = "Regolith Excavation", quest = "E1-PROPLOOP",
          kind = "invention", prereqs = { "E1-PL-01" }, cost = "M", payoff = "building",
          condition = "research", unlocks = "Surface/Ice extraction rig", status = "sketch" },
        { id = "E1-PL-04", name = "Regolith Excavation II", quest = "E1-PROPLOOP",
          kind = "tier", tier = 2, prereqs = { "E1-PL-03" }, cost = "S", payoff = "efficiency",
          condition = "research", unlocks = "Throughput up", status = "sketch" },
        { id = "E1-PL-05", name = "Regolith Excavation III", quest = "E1-PROPLOOP",
          kind = "tier", tier = 3, prereqs = { "E1-PL-04" }, cost = "M", payoff = "efficiency",
          condition = "research", unlocks = "Throughput up", status = "sketch" },
        { id = "E1-PL-06", name = "Water Extraction (thermal)", quest = "E1-PROPLOOP",
          kind = "invention", prereqs = { "E1-PL-03" }, cost = "M", payoff = "recipe",
          condition = "research", unlocks = "Regolith/ice -> raw water", status = "sketch" },
        { id = "E1-PL-07", name = "Water Extraction II", quest = "E1-PROPLOOP",
          kind = "tier", tier = 2, prereqs = { "E1-PL-06" }, cost = "S", payoff = "efficiency",
          condition = "research", unlocks = "Yield up", status = "sketch" },
        { id = "E1-PL-08", name = "Water Purification", quest = "E1-PROPLOOP",
          kind = "invention", prereqs = { "E1-PL-06" }, cost = "M", payoff = "recipe",
          condition = "research", unlocks = "Raw water -> clean water", status = "sketch" },
        { id = "E1-PL-09", name = "Water Electrolysis", quest = "E1-PROPLOOP",
          kind = "invention", prereqs = { "E1-PL-08" }, cost = "M", payoff = "recipe",
          condition = "research", unlocks = "Water -> LH2 + LOX (the keystone step)", status = "sketch" },
        { id = "E1-PL-10", name = "Water Electrolysis II", quest = "E1-PROPLOOP",
          kind = "tier", tier = 2, prereqs = { "E1-PL-09" }, cost = "S", payoff = "efficiency",
          condition = "research", unlocks = "Energy per kg down", status = "sketch" },
        { id = "E1-PL-11", name = "Cryogenic Liquefaction", quest = "E1-PROPLOOP",
          kind = "invention", prereqs = { "E1-PL-09" }, cost = "M", payoff = "recipe",
          condition = "research", unlocks = "Gas -> liquid H2/O2", status = "sketch" },
        { id = "E1-PL-12", name = "Cryogenic Storage", quest = "E1-PROPLOOP",
          kind = "invention", prereqs = { "E1-PL-11" }, cost = "M", payoff = "building",
          condition = "research", unlocks = "Depot tank; boil-off baseline", status = "sketch" },
        { id = "E1-PL-13", name = "Cryogenic Storage II", quest = "E1-PROPLOOP",
          kind = "tier", tier = 2, prereqs = { "E1-PL-12" }, cost = "S", payoff = "efficiency",
          condition = "research", unlocks = "Boil-off down", status = "sketch" },
        { id = "E1-PL-14", name = "Cryogenic Storage III", quest = "E1-PROPLOOP",
          kind = "tier", tier = 3, prereqs = { "E1-PL-13" }, cost = "M", payoff = "efficiency",
          condition = "research", unlocks = "Boil-off down", status = "sketch" },
        { id = "E1-PL-15", name = "Sabatier Reactor", quest = "E1-PROPLOOP",
          kind = "invention", prereqs = { "E1-PL-09" }, cost = "M", payoff = "recipe",
          condition = "research", unlocks = "CO2 + H2 -> methane (the methane tell)", status = "sketch" },
        { id = "E1-PL-16", name = "Sabatier II", quest = "E1-PROPLOOP",
          kind = "tier", tier = 2, prereqs = { "E1-PL-15" }, cost = "S", payoff = "efficiency",
          condition = "research", unlocks = "Yield up", status = "sketch" },
        { id = "E1-PL-17", name = "Methane Liquefaction", quest = "E1-PROPLOOP",
          kind = "invention", prereqs = { "E1-PL-15" }, cost = "M", payoff = "recipe",
          condition = "research", unlocks = "Methalox propellant path", status = "sketch" },
        { id = "E1-PL-18", name = "Autonomous Mining Rig", quest = "E1-PROPLOOP",
          kind = "invention", prereqs = { "E1-PL-05", "L-AU-01" }, cost = "M", payoff = "efficiency",
          condition = "research", unlocks = "Workforce scalar down (cross-links the Automation line)", status = "sketch" },
        { id = "E1-PL-19", name = "Autonomous Rig II", quest = "E1-PROPLOOP",
          kind = "tier", tier = 2, prereqs = { "E1-PL-18" }, cost = "S", payoff = "efficiency",
          condition = "research", unlocks = "Workforce scalar down", status = "sketch" },
        { id = "E1-PL-20", name = "In-Situ Tank Fabrication", quest = "E1-PROPLOOP",
          kind = "invention", prereqs = { "E1-PL-12" }, cost = "M", payoff = "building",
          condition = "stockpile", unlocks = "Local depot without Earth lift (needs regolith/metal on body)", status = "sketch" },
        { id = "E1-PL-21", name = "Orbital Propellant Depot", quest = "E1-PROPLOOP",
          kind = "invention", prereqs = { "E1-PL-20", "E1-OR-02" }, cost = "L", payoff = "building",
          condition = "structure", unlocks = "The demand-sink node (cross-quest dep: Orbital Port)", status = "sketch" },
        { id = "E1-PL-22", name = "Depot Network II", quest = "E1-PROPLOOP",
          kind = "tier", tier = 2, prereqs = { "E1-PL-21" }, cost = "M", payoff = "efficiency",
          condition = "research", unlocks = "Transfer loss down", status = "sketch" },
        { id = "E1-PL-24", name = "Boil-off Recovery", quest = "E1-PROPLOOP",
          kind = "invention", prereqs = { "E1-PL-14" }, cost = "M", payoff = "efficiency",
          condition = "research", unlocks = "Reclaim vented gas", status = "sketch" },
        { id = "E1-PL-25", name = "Propellant Market Hook", quest = "E1-PROPLOOP",
          kind = "invention", prereqs = { "E1-PL-21" }, cost = "S", payoff = "enabling",
          condition = "market", unlocks = "Depot sells propellant into the space market (creates the price signal)", status = "sketch" },
        { id = "E1-PL-23", name = "Closed-Loop Certification", quest = "E1-PROPLOOP",
          kind = "capstone", prereqs = { "E1-PL-21", "E1-PL-17" }, cost = "XL", payoff = "gate",
          condition = "surplus", unlocks = "Quest goal: propellant loop closed on one off-world body (sustained excess >= threshold for N ticks)", status = "sketch" },

        -- ----------------------------------------------- E1-ORBITAL (stub, 4)
        { id = "E1-OR-01", name = "Orbital Assembly", quest = "E1-ORBITAL",
          kind = "invention", prereqs = { "E0-RK-05" }, cost = "L", payoff = "building",
          condition = "research", unlocks = "Assembly Plant", status = "stub" },
        { id = "E1-OR-02", name = "Orbital Port", quest = "E1-ORBITAL",
          kind = "invention", prereqs = { "E1-OR-01" }, cost = "L", payoff = "building",
          condition = "research", unlocks = "Orbital Port", status = "stub" },
        { id = "E1-OR-03", name = "Station-Keeping II", quest = "E1-ORBITAL",
          kind = "tier", tier = 2, prereqs = { "E1-OR-01" }, cost = "S", payoff = "efficiency",
          condition = "research", unlocks = "Orbital maintenance down", status = "stub" },
        { id = "E1-OR-04", name = "Orbital Industrial Base", quest = "E1-ORBITAL",
          kind = "capstone", prereqs = { "E1-OR-02" }, cost = "XL", payoff = "gate",
          condition = "structure", unlocks = "Quest goal: Assembly Plant + Orbital Port operating together", status = "stub" },

        -- --------------------------------------------------- L-LOG (stub, 4)
        { id = "L-LG-01", name = "Freight Optimisation", quest = "L-LOG",
          kind = "invention", prereqs = {}, cost = "M", payoff = "efficiency",
          condition = "research", unlocks = "Convoy cost per leg down", status = "stub" },
        { id = "L-LG-02", name = "Ion Propulsion", quest = "L-LOG",
          kind = "invention", prereqs = { "L-LG-01" }, cost = "L", payoff = "efficiency",
          condition = "research", unlocks = "Propellant per space leg down; slower transit", status = "stub" },
        { id = "L-LG-03", name = "Ion Propulsion II", quest = "L-LOG",
          kind = "tier", tier = 2, prereqs = { "L-LG-02" }, cost = "M", payoff = "efficiency",
          condition = "research", unlocks = "Thrust up (mid-tier must carry a real trade-off — the TI lesson)", status = "stub" },
        { id = "L-LG-04", name = "Nuclear-Thermal Propulsion", quest = "L-LOG",
          kind = "invention", prereqs = { "L-LG-02" }, cost = "XL", payoff = "efficiency",
          condition = "research", unlocks = "High-thrust deep-space transit", status = "parked" },

        -- -------------------------------------------------- L-AUTO (stub, 3)
        { id = "L-AU-01", name = "Industrial Automation", quest = "L-AUTO",
          kind = "invention", prereqs = {}, cost = "M", payoff = "efficiency",
          condition = "research", unlocks = "Workforce scalar down across extraction", status = "stub" },
        { id = "L-AU-02", name = "Industrial Automation II", quest = "L-AUTO",
          kind = "tier", tier = 2, prereqs = { "L-AU-01" }, cost = "S", payoff = "efficiency",
          condition = "research", unlocks = "Workforce scalar down further", status = "stub" },
        { id = "L-AU-03", name = "Autonomous Operations", quest = "L-AUTO",
          kind = "invention", prereqs = { "L-AU-01" }, cost = "L", payoff = "efficiency",
          condition = "research", unlocks = "Remote/unmanned building operation off-world", status = "stub" },
    },
}
