-- Mock tech / quest tree (BL-087). DATA ONLY — the tech system is post-prototype
-- (BL-087 resolution 6); nothing in the simulation reads this. It exists so the
-- F9 read-only viewer can show the tree while the design is fresh.
--
-- Schema (mirrors docs/research/ERA1_TECH_LANDSCAPE.md / docs/research/TECH_EFFECTS.md):
--   quest: id, name, era, type ("gate"|"standing"), thread, thesis, capstone,
--          opens (quest ids the capstone unlocks — capstones open QUEST TREES,
--          not Eras, per the 2026-07-08 Era reframe), status
--   tech:  id, name, quest, kind ("invention"|"tier"|"capstone"), tier,
--          prereqs (tech ids; MAY cross quests, sparingly), cost (S/M/L/XL,
--          default M), payoff (gate|resource|building|recipe|efficiency|enabling),
--          condition (research|structure|stockpile|market|surplus|era|deed —
--          "deed" added 2026-08-05: a tangible in-game action, not a state
--          predicate; see ERA1_TECH_LANDSCAPE.md § The deed primitive),
--          unlocks, status
--
-- Era 0 section: shape rules from the 2026-07-08 resolutions (mostly a binary
-- tree with dead-end leaves; cross-quest prereqs sparing and deliberate;
-- economic conditions reserved for capstones + marquee nodes). Unchanged.
--
-- Era 1 section: REWRITTEN 2026-08-06 to transcribe "The Era 1 tree — first
-- draft" (ERA1_TECH_LANDSCAPE.md, 2026-08-05) — five sectors (Launch,
-- Volatiles, Mobility, Yards, Extraction) x three rings (R1 Reach, R2
-- Foothold, R3 Industry), four keystone forks each opened by a DEED rather
-- than a research/structure/market predicate, with permanent branch exclusion.
-- STATUS: "sketch" everywhere in this section — Ben has explicitly not yet
-- reviewed the node list ("the shape is the argument; the node list is a
-- starting point, not a proposal" — ERA1_TECH_LANDSCAPE.md). This viewer
-- rendering IS that review's first concrete look, not a ratification.
--
-- Era -1 Antiquity section: ADDED 2026-08-06 (BL-310, NR-054) — see the block
-- comment ahead of the ANT- quests below. status="derived" (not "sketch"):
-- this content isn't a draft awaiting review, it's a mechanical transcription
-- of an already-canonical, already-lint-checked store.

tech_tree = {
    quests = {
    -- ================================================================
    -- ERA -1 ANTIQUITY (BL-310, 2026-08-06) - read-only HISTORY, not a
    -- player-facing tree (NR-054, Ben: render it, even just as a
    -- history). Mechanically transcribed from the canonical store,
    -- docs/research/ancient_tech_ladder.json (BL-296/BL-307) - do not
    -- hand-edit these entries; regenerate via the transcription script
    -- if the JSON changes. Rings are the authored band (T1=1..T6=6),
    -- not graph depth. SIMPLIFICATION, flagged rather than silently
    -- dropped: the JSON's 12 vertex_quests and 4 crossings are NOT
    -- point objects (they name a ring boundary or a roster swap, not a
    -- single node) and are not transcribed here - a "just history" first
    -- pass renders nodes + keystones only. status="derived" throughout:
    -- nothing here is ever chosen, only derived (BL-274's endowment/
    -- diffusion mechanism) - the whole reason NR-054 confirmed this stays
    -- a history, not a research tree.

    { id = "ANT-MA", name = "Materials", era = -1, type = "gate",
      thread = "Materials",
      thesis = "Derived by the Era -1 sim from endowment and contact - never clicked.",
      capstone = "", opens = {}, status = "derived" },
    { id = "ANT-EN", name = "Energy", era = -1, type = "gate",
      thread = "Energy",
      thesis = "Derived by the Era -1 sim from endowment and contact - never clicked.",
      capstone = "", opens = {}, status = "derived" },
    { id = "ANT-TR", name = "Transport", era = -1, type = "gate",
      thread = "Transport",
      thesis = "Derived by the Era -1 sim from endowment and contact - never clicked.",
      capstone = "", opens = {}, status = "derived" },
    { id = "ANT-IN", name = "Institutions", era = -1, type = "gate",
      thread = "Institutions",
      thesis = "Derived by the Era -1 sim from endowment and contact - never clicked.",
      capstone = "", opens = {}, status = "derived" },
    { id = "ANT-MIL", name = "Military", era = -1, type = "gate",
      thread = "Military",
      thesis = "Derived by the Era -1 sim from endowment and contact - never clicked.",
      capstone = "", opens = {}, status = "derived" },
    { id = "ANT-ME", name = "Medicine", era = -1, type = "gate",
      thread = "Medicine",
      thesis = "Derived by the Era -1 sim from endowment and contact - never clicked.",
      capstone = "", opens = {}, status = "derived" },
    { id = "ANT-AG", name = "Agriculture", era = -1, type = "gate",
      thread = "Agriculture",
      thesis = "Derived by the Era -1 sim from endowment and contact - never clicked.",
      capstone = "", opens = {}, status = "derived" },

        -- ---------------------------------------------------------------- Era 0
        { id = "E0-HEAVY", name = "Heavy Industry", era = 0, type = "gate",
          thread = "Industry",
          thesis = "A steel / chemicals / refining base broad enough to build rockets from.",
          capstone = "E0-HI-04", opens = { "E0-ROCKET" }, status = "stub" },

        { id = "E0-ELEC", name = "Electronics & Computing", era = 0, type = "gate",
          thread = "Compute",
          thesis = "Info-Age footing; compute is the input the R&D Lab consumes.",
          capstone = "E0-EC-04", opens = {}, status = "stub" },

        { id = "E0-ROCKET", name = "Rocketry", era = 0, type = "gate",
          thread = "Launch",
          thesis = "An operable launch complex — the condition set ERAS.md records, re-read as a quest-tree gate.",
          capstone = "E0-RK-05",
          opens = { "E1-LAUNCH", "E1-VOLATILES", "E1-MOBILITY", "E1-YARDS", "E1-EXTRACTION" },
          status = "stub" },

        -- ---------------------------------------------------------------- Era 1
        -- Five sectors (ERA1_TECH_LANDSCAPE.md § Shape). Each sector's tree
        -- carries R1/R2/R3 rings; four of the five carry a keystone fork
        -- (Mobility does not). "capstone" here names the sector's KEYSTONE
        -- tech (the fork), not a terminal gate — no Era-2 hook exists yet
        -- (§ What this draft deliberately does not do).
        { id = "E1-LAUNCH", name = "Launch", era = 1, type = "gate",
          thread = "Launch",
          thesis = "Cadence, reuse, lift cost per kg — can you get there at all?",
          capstone = "E1-LA-KEYSTONE", opens = {}, status = "sketch" },

        { id = "E1-VOLATILES", name = "Volatiles", era = 1, type = "gate",
          thread = "ISRU",
          thesis = "Water, electrolysis, the propellant loop — can you make something locally?",
          capstone = "E1-VO-KEYSTONE", opens = {}, status = "sketch" },

        { id = "E1-MOBILITY", name = "Mobility", era = 1, type = "gate",
          thread = "Propulsion",
          thesis = "Transfer cost, the propellant tax, engine classes. No keystone fork — a plain depth line.",
          capstone = "", opens = {}, status = "sketch" },

        { id = "E1-YARDS", name = "Yards", era = 1, type = "gate",
          thread = "Orbital Construction",
          thesis = "Orbital construction, assembly, the port as trade participant.",
          capstone = "E1-YA-KEYSTONE", opens = {}, status = "sketch" },

        { id = "E1-EXTRACTION", name = "Extraction", era = 1, type = "gate",
          thread = "Off-world deposits",
          thesis = "Regolith, iron-nickel, PGM — does it pay for itself, can it supply someone else?",
          capstone = "E1-EX-KEYSTONE", opens = {}, status = "sketch" },

        -- --------------------------------------------------------- Standing lines
        { id = "L-LOG", name = "Logistics", era = 0, type = "standing",
          thread = "Propulsion",
          thesis = "The convoy propellant tax, deepened forever: chemical, ion, nuclear-thermal (parked).",
          capstone = "", opens = {}, status = "stub" },

        { id = "L-AUTO", name = "Economy & Automation", era = 0, type = "standing",
          thread = "Power & Automation",
          thesis = "The workforce-scalar and power substrate behind every quest. Crosses Extraction at R3 to carry the Autonomy Doctrine's second branch.",
          capstone = "", opens = {}, status = "stub" },

        { id = "L-MIL", name = "Military", era = 0, type = "standing",
          thread = "Military",
          thesis = "Largely reserved until the combat system is mapped — but it carries the prototype's one EARNABLE tech (E0-ML-01, BL-344), because the first thing a technology should be able to unlock is not another factory.",
          capstone = "", opens = {}, status = "stub" },
    },

    techs = {

        -- --------------------------------------------- Antiquity (derived, history-only)
        -- Materials (15)
        { id = "T1-MA-01", name = "Bloomery Iron", quest = "ANT-MA",
          kind = "invention", tier = 1, prereqs = {  }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: ore_q. Diffusion: capacity. Earth ref: mature by 0 CE", status = "derived" },
        { id = "T1-MA-02", name = "Structural Masonry & Cement", quest = "ANT-MA",
          kind = "invention", tier = 1, prereqs = {  }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: practice. Earth ref: 1st c. concrete", status = "derived" },
        { id = "T2-MA-01", name = "Pattern-Forged Steel", quest = "ANT-MA",
          kind = "invention", tier = 2, prereqs = { "T1-MA-01" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: ore_q+fuel. Diffusion: capacity. Earth ref: crucible/pattern steels", status = "derived" },
        { id = "T2-MA-02", name = "Paper", quest = "ANT-MA",
          kind = "invention", tier = 2, prereqs = {  }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: capacity. Earth ref: 105 CE, west by 8th–13th c. — the diffusion showpiece", status = "derived" },
        { id = "T3-MA-01", name = "Blast Furnace (cast iron)", quest = "ANT-MA",
          kind = "invention", tier = 3, prereqs = { "T2-MA-01" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: ore_q+fuel. Diffusion: capacity. Earth ref: 12th–14th c. Europe; earlier east", status = "derived" },
        { id = "T3-MA-02", name = "Mechanical Clockwork", quest = "ANT-MA",
          kind = "invention", tier = 3, prereqs = {  }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: ore_q. Diffusion: capacity. Earth ref: precision mechanism tradition", status = "derived" },
        { id = "T4-MA-01", name = "Movable-Type Press", quest = "ANT-MA",
          kind = "invention", tier = 4, prereqs = { "T2-MA-02", "T3-MA-02" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: capacity. Effects: modifier->practice diffusion rate; institution->administrative capacity. Earth ref: 1450s; information cost collapses", status = "derived" },
        { id = "T4-MA-02", name = "Cast Ordnance", quest = "ANT-MA",
          kind = "invention", tier = 4, prereqs = { "T3-MA-01" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: ore_q+fuel. Diffusion: capacity. Effects: unlock->siege/artillery roster row. Earth ref: foundry cannon", status = "derived" },
        { id = "T4-MA-03", name = "Precision Instruments", quest = "ANT-MA",
          kind = "invention", tier = 4, prereqs = { "T3-MA-02" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: capacity. Effects: unlock->machinery recipe precursor; modifier->construction pacing. Earth ref: lenses, gauges, screw threads — T5's toolroom", status = "derived" },
        { id = "T5-MA-01", name = "Coke Smelting", quest = "ANT-MA",
          kind = "invention", tier = 5, prereqs = { "T3-MA-01" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: ore_q+fuel. Diffusion: capacity. Effects: upgrade->steel recipe at scale; retire->the charcoal route (Coke branch only). Earth ref: breaks the charcoal ceiling", status = "derived" },
        { id = "T5-MA-02", name = "Machine Tools", quest = "ANT-MA",
          kind = "invention", tier = 5, prereqs = { "T4-MA-03", "T5-EN-01" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: ore_q. Diffusion: capacity. Effects: unlock->machinery recipe; modifier->construction pacing. Earth ref: interchangeable parts; capacity that builds capacity", status = "derived" },
        { id = "T5-MA-03", name = "Converter Steel", quest = "ANT-MA",
          kind = "invention", tier = 5, prereqs = { "T5-MA-01" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: ore_q+fuel. Diffusion: capacity. Effects: upgrade->steel output and cost; unlock->alloys recipe. Earth ref: 1856; cheap steel", status = "derived" },
        { id = "T5-MA-04", name = "Framed Construction & Cement", quest = "ANT-MA",
          kind = "invention", tier = 5, prereqs = { "T5-MA-03" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: capacity. Effects: access->steeper landforms; unlock->Warehouse / Storage Depot. Earth ref: iron-framed mills → steel frame; the industrial city", status = "derived" },
        { id = "T6-MA-01", name = "Synthetic Chemistry", quest = "ANT-MA",
          kind = "invention", tier = 6, prereqs = { "T5-MA-03" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: fuel. Diffusion: capacity. Earth ref: dyes → polymers → explosives", status = "derived" },
        { id = "T6-MA-02", name = "Fixed-Nitrogen Synthesis", quest = "ANT-MA",
          kind = "invention", tier = 6, prereqs = { "T6-MA-01" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: fuel. Diffusion: capacity. Earth ref: 1913; food ceiling lifts — feeds BL-273 growth", status = "derived" },
        -- Energy (9)
        { id = "T1-EN-01", name = "Water Wheel", quest = "ANT-EN",
          kind = "invention", tier = 1, prereqs = {  }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: arable. Diffusion: capacity. Earth ref: 1st c. — first non-muscle prime mover", status = "derived" },
        { id = "T2-EN-01", name = "Windmill", quest = "ANT-EN",
          kind = "invention", tier = 2, prereqs = { "T1-EN-01" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: capacity. Earth ref: 9th–12th c.", status = "derived" },
        { id = "T3-EN-01", name = "Mill Networks", quest = "ANT-EN",
          kind = "invention", tier = 3, prereqs = { "T1-EN-01", "T2-EN-01" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: arable. Diffusion: capacity. Earth ref: cam/crank trip-hammers, fulling", status = "derived" },
        { id = "T4-EN-01", name = "Deep Mining & Drainage", quest = "ANT-EN",
          kind = "invention", tier = 4, prereqs = { "T3-EN-01" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: fuel. Diffusion: capacity. Effects: access->deposits below the shallow band; modifier->mine output. Earth ref: the pump problem that asks for steam", status = "derived" },
        { id = "T4-EN-02", name = "Coal Haulage & Urban Fuel", quest = "ANT-EN",
          kind = "invention", tier = 4, prereqs = { "T3-TR-02" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: fuel. Diffusion: capacity. Effects: resource->coal as a bulk traded good; reach->coastal bulk haulage. Earth ref: coastal coal trade; urban fuel demand precedes the engine", status = "derived" },
        { id = "T5-EN-01", name = "Atmospheric & Rotative Steam", quest = "ANT-EN",
          kind = "invention", tier = 5, prereqs = { "T4-EN-01", "T4-MA-03" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: fuel. Diffusion: capacity. Effects: unlock->Power Plant coal recipe; modifier->output per worker. Earth ref: 1712 → 1780s; the master node", status = "derived" },
        { id = "T5-EN-02", name = "High-Pressure & Compound Engines", quest = "ANT-EN",
          kind = "invention", tier = 5, prereqs = { "T5-EN-01", "T5-MA-02" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: fuel. Diffusion: capacity. Effects: upgrade->Power Plant tier. Earth ref: power leaves the engine house; rail and ships become possible", status = "derived" },
        { id = "T6-EN-01", name = "Electrification", quest = "ANT-EN",
          kind = "invention", tier = 6, prereqs = { "T5-EN-01" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: fuel. Diffusion: capacity. Earth ref: grid power; the second prime-mover shift", status = "derived" },
        { id = "T6-EN-02", name = "Internal Combustion & Oil", quest = "ANT-EN",
          kind = "invention", tier = 6, prereqs = { "T5-MA-02" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: fuel. Diffusion: capacity. Earth ref: oil displaces coal at the margin", status = "derived" },
        -- Transport (11)
        { id = "T1-TR-01", name = "Engineered Road Network", quest = "ANT-TR",
          kind = "invention", tier = 1, prereqs = { "T1-MA-02" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: capacity. Earth ref: imperial road nets", status = "derived" },
        { id = "T1-TR-02", name = "Deep-Hull Sail", quest = "ANT-TR",
          kind = "invention", tier = 1, prereqs = {  }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: coastal. Diffusion: capacity. Earth ref: Mediterranean/monsoon trade", status = "derived" },
        { id = "T2-TR-01", name = "Lateen & Long-Range Rig", quest = "ANT-TR",
          kind = "invention", tier = 2, prereqs = { "T1-TR-02" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: coastal. Diffusion: capacity. Earth ref: ocean-capable coasting", status = "derived" },
        { id = "T3-TR-01", name = "Compass & Sternpost Rudder", quest = "ANT-TR",
          kind = "invention", tier = 3, prereqs = { "T2-TR-01" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: coastal. Diffusion: practice. Earth ref: dead-reckoning seafaring", status = "derived" },
        { id = "T3-TR-02", name = "Ocean-Rated Hulls", quest = "ANT-TR",
          kind = "invention", tier = 3, prereqs = { "T3-TR-01" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: coastal. Diffusion: capacity. Earth ref: cog → carrack line", status = "derived" },
        { id = "T4-TR-01", name = "Full-Rigged Ship", quest = "ANT-TR",
          kind = "invention", tier = 4, prereqs = { "T3-TR-02" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: coastal. Diffusion: capacity. Effects: reach->inter-region route range; upgrade->port throughput. Earth ref: global range", status = "derived" },
        { id = "T4-TR-02", name = "Celestial Navigation", quest = "ANT-TR",
          kind = "invention", tier = 4, prereqs = { "T3-TR-01", "T4-MA-03" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: coastal. Diffusion: practice. Effects: intel->route reliability; reach->open-ocean legs. Earth ref: longitude closes the ocean", status = "derived" },
        { id = "T5-TR-01", name = "Railway", quest = "ANT-TR",
          kind = "invention", tier = 5, prereqs = { "T5-EN-01", "T5-MA-01" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: fuel. Diffusion: capacity. Effects: unlock->inland_logistics_hub; reach->intra-body haul cost. Earth ref: interior distance collapses", status = "derived" },
        { id = "T5-TR-02", name = "Steamship", quest = "ANT-TR",
          kind = "invention", tier = 5, prereqs = { "T5-EN-01" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: coastal. Diffusion: capacity. Effects: upgrade->port throughput; intel->route staleness (route_fresh_ticks). Earth ref: schedule replaces season", status = "derived" },
        { id = "T6-TR-01", name = "Automotive Transport", quest = "ANT-TR",
          kind = "invention", tier = 6, prereqs = { "T6-EN-02" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: capacity. Earth ref: road freight; artifact form diffuses instantly", status = "derived" },
        { id = "T6-TR-02", name = "Flight", quest = "ANT-TR",
          kind = "invention", tier = 6, prereqs = { "T6-EN-02", "T5-MA-02" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: capacity. Earth ref: 1903 → jets by the epoch", status = "derived" },
        -- Institutions (14)
        { id = "T1-IN-01", name = "Codified Law & Census", quest = "ANT-IN",
          kind = "invention", tier = 1, prereqs = {  }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: practice. Earth ref: the Stage 1 floor", status = "derived" },
        { id = "T1-IN-02", name = "Coinage at Scale", quest = "ANT-IN",
          kind = "invention", tier = 1, prereqs = { "T1-IN-01" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: ore_q. Diffusion: practice. Earth ref: monetised economies", status = "derived" },
        { id = "T2-IN-01", name = "Positional Arithmetic", quest = "ANT-IN",
          kind = "invention", tier = 2, prereqs = { "T2-MA-02" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: practice. Earth ref: the zero; calculation cheapens", status = "derived" },
        { id = "T2-IN-02", name = "Endowed Scholarship", quest = "ANT-IN",
          kind = "invention", tier = 2, prereqs = { "T1-IN-01" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: practice. Earth ref: institutional memory survives dynasties", status = "derived" },
        { id = "T3-IN-01", name = "Credit Instruments & Double Entry", quest = "ANT-IN",
          kind = "invention", tier = 3, prereqs = { "T2-IN-01" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: practice. Earth ref: bills of exchange; Stage 3's seed", status = "derived" },
        { id = "T3-IN-02", name = "Chartered Companies", quest = "ANT-IN",
          kind = "invention", tier = 3, prereqs = { "T3-IN-01", "T1-IN-01" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: practice. Earth ref: the Charter Age node — Stage 1's apex", status = "derived" },
        { id = "T4-IN-01", name = "Empirical Method", quest = "ANT-IN",
          kind = "invention", tier = 4, prereqs = { "T4-MA-01" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: practice. Effects: modifier->invention roll; institution->research capacity. Earth ref: knowledge compounds openly", status = "derived" },
        { id = "T4-IN-02", name = "Joint-Stock & Public Credit", quest = "ANT-IN",
          kind = "invention", tier = 4, prereqs = { "T3-IN-02" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: practice. Effects: institution->public credit; debt interest terms. Earth ref: Stage 3 lands: capital disciplines the sovereign", status = "derived" },
        { id = "T4-IN-03", name = "Patent Grants", quest = "ANT-IN",
          kind = "invention", tier = 4, prereqs = { "T4-IN-01" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: practice. Effects: modifier->invention roll; institution->property in invention. Earth ref: invention becomes property; modifies the invention roll", status = "derived" },
        { id = "T5-IN-01", name = "Telegraph", quest = "ANT-IN",
          kind = "invention", tier = 5, prereqs = { "T5-MA-02", "T5-TR-01" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: capacity. Effects: intel->activity-fog freshness window; unlock->market pulse at range. Earth ref: information detaches from transport; rail signalling drives the net", status = "derived" },
        { id = "T5-IN-02", name = "Mass Schooling & Press", quest = "ANT-IN",
          kind = "invention", tier = 5, prereqs = { "T4-MA-01" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: practice. Effects: modifier->workforce efficiency; institution->the literate substrate. Earth ref: literate workforce — T6's floor", status = "derived" },
        { id = "T5-IN-03", name = "General Incorporation", quest = "ANT-IN",
          kind = "invention", tier = 5, prereqs = { "T4-IN-02" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: practice. Effects: institution->chartered corporate form. Earth ref: chartering by registration, not by grant — the campaign's premise", status = "derived" },
        { id = "T6-IN-01", name = "Broadcast", quest = "ANT-IN",
          kind = "invention", tier = 6, prereqs = { "T5-IN-01" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: capacity. Earth ref: radio: artifact diffuses, capacity doesn't", status = "derived" },
        { id = "T6-IN-02", name = "Early Computing", quest = "ANT-IN",
          kind = "invention", tier = 6, prereqs = { "T5-MA-02", "T6-EN-01" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: capacity. Earth ref: the epoch's frontier; feeds E0-ELEC", status = "derived" },
        -- Military (6)
        { id = "T1-MIL", name = "Regime: massed iron infantry, siegecraft", quest = "ANT-MIL",
          kind = "regime", tier = 1, prereqs = { "T1-MA-01" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: ore_q. Earth ref: BL-274 rows. Roster: BL-274", status = "derived" },
        { id = "T2-MIL", name = "Regime: stirrup heavy cavalry, fortress", quest = "ANT-MIL",
          kind = "regime", tier = 2, prereqs = {  }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: grassland. Earth ref: BL-274 rows. Roster: BL-274", status = "derived" },
        { id = "T3-MIL", name = "Regime: crossbow/plate; first gunpowder", quest = "ANT-MIL",
          kind = "regime", tier = 3, prereqs = { "T3-MA-01" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: fuel. Earth ref: BL-274 rows; powder needs the energy proxy. Roster: BL-274", status = "derived" },
        { id = "T4-MIL", name = "Regime: flintlock line, artillery fortress, broadside fleet", quest = "ANT-MIL",
          kind = "regime", tier = 4, prereqs = { "T4-MA-02" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: fuel. Effects: unlock->roster turnover; retire->medieval roster rows. Earth ref: BL-274 rows. Roster: BL-274", status = "derived" },
        { id = "T5-MIL", name = "Regime: rifle, ironclad, general staff", quest = "ANT-MIL",
          kind = "regime", tier = 5, prereqs = { "T5-MA-03" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: ore_q+fuel. Effects: unlock->roster turnover; retire->flintlock roster rows; doctrine->general staff. Earth ref: BL-274 rows. Roster: BL-274", status = "derived" },
        { id = "T6-MIL", name = "Regime: armour, airpower, radar; missiles/atomics at the frontier", quest = "ANT-MIL",
          kind = "regime", tier = 6, prereqs = { "T6-MA-01", "T6-TR-02" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: fuel. Earth ref: BL-274 rows. Roster: BL-274", status = "derived" },
        -- Medicine (6)
        { id = "T1-ME-01", name = "Physicians' Canon", quest = "ANT-ME",
          kind = "invention", tier = 1, prereqs = { "T1-IN-01" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: practice. Earth ref: Galenic-style corpus", status = "derived" },
        { id = "T2-ME-01", name = "Founded Infirmaries", quest = "ANT-ME",
          kind = "invention", tier = 2, prereqs = { "T1-ME-01" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: practice. Earth ref: endowed hospitals; care institutionalises", status = "derived" },
        { id = "T3-ME-01", name = "Quarantine Doctrine", quest = "ANT-ME",
          kind = "invention", tier = 3, prereqs = { "T1-ME-01" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: practice. Earth ref: plague response; drawdown mitigation", status = "derived" },
        { id = "T4-ME-01", name = "Preventive Inoculation", quest = "ANT-ME",
          kind = "invention", tier = 4, prereqs = { "T3-ME-01" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: practice. Effects: modifier->mortality rate. Earth ref: 18th c.; mortality falls before germ theory explains it", status = "derived" },
        { id = "T5-ME-01", name = "Germ Theory & Sanitation", quest = "ANT-ME",
          kind = "invention", tier = 5, prereqs = { "T4-IN-01" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: practice. Effects: modifier->demographic growth; modifier->tile hazard penalty. Earth ref: mortality falls ahead of wealth", status = "derived" },
        { id = "T6-ME-01", name = "Antibiotics & Mass Vaccination", quest = "ANT-ME",
          kind = "invention", tier = 6, prereqs = { "T5-ME-01", "T6-MA-01" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: practice+artifact. Earth ref: demographic transition completes", status = "derived" },
        -- Agriculture (10)
        { id = "T1-AG-01", name = "Iron-Shod Plough", quest = "ANT-AG",
          kind = "invention", tier = 1, prereqs = {  }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: practice. Earth ref: widespread by 0 CE", status = "derived" },
        { id = "T1-AG-02", name = "Irrigation Works", quest = "ANT-AG",
          kind = "invention", tier = 1, prereqs = {  }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: arable. Diffusion: capacity. Earth ref: canal/qanat systems", status = "derived" },
        { id = "T2-AG-01", name = "Mouldboard Plough & Harness", quest = "ANT-AG",
          kind = "invention", tier = 2, prereqs = { "T1-AG-01" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: arable. Diffusion: practice. Earth ref: heavy-soil opening, 6th–9th c.", status = "derived" },
        { id = "T2-AG-02", name = "Three-Field Rotation", quest = "ANT-AG",
          kind = "invention", tier = 2, prereqs = { "T2-AG-01" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: practice. Earth ref: ~50% arable output gain", status = "derived" },
        { id = "T3-AG-01", name = "Land Reclamation", quest = "ANT-AG",
          kind = "invention", tier = 3, prereqs = { "T2-AG-02" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: arable. Diffusion: capacity. Earth ref: polders, terracing, drainage", status = "derived" },
        { id = "T4-AG-01", name = "Crop-Package Exchange", quest = "ANT-AG",
          kind = "invention", tier = 4, prereqs = { "T3-TR-02" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: practice. Effects: access->Farm terrain compositions; modifier->farm output. Earth ref: inter-continental crop transfer", status = "derived" },
        { id = "T4-AG-02", name = "Convertible Husbandry", quest = "ANT-AG",
          kind = "invention", tier = 4, prereqs = { "T2-AG-02" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: arable. Diffusion: practice. Effects: modifier->farm output per worker. Earth ref: fodder rotation; feeds T5 workforce release", status = "derived" },
        { id = "T5-AG-01", name = "Farm Mechanisation", quest = "ANT-AG",
          kind = "invention", tier = 5, prereqs = { "T5-MA-02" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: arable. Diffusion: capacity. Effects: modifier->farm output per worker; institution->workforce release to industry. Earth ref: reaper line; releases workforce to industry", status = "derived" },
        { id = "T5-AG-02", name = "Soil Chemistry & Fertiliser Trade", quest = "ANT-AG",
          kind = "invention", tier = 5, prereqs = { "T5-TR-02", "T4-IN-01" }, cost = "",
          payoff = "", condition = "diffusion", unlocks = "Diffusion: practice+artifact. Effects: resource->fertiliser as a traded good; modifier->farm yield. Earth ref: 1840s; yield stops being bounded by the local nitrogen cycle", status = "derived" },
        { id = "T6-AG-01", name = "Tractor & Fertiliser Package", quest = "ANT-AG",
          kind = "invention", tier = 6, prereqs = { "T6-EN-02", "T6-MA-02" }, cost = "",
          payoff = "", condition = "endowment", unlocks = "Gate: arable. Diffusion: capacity. Earth ref: single-digit % farm workforce", status = "derived" },

        -- Keystones (5) - creed-picked forks for AI nations (HISTORY.md); no
        -- interactive branch here (read-only history). Positioned at their
        -- band/domain; not wired into the prereq graph (the JSON keystone
        -- record carries no prereqs field - a documented simplification, not
        -- an omission).
        { id = "KS-GRANARY", name = "Granary Doctrine", quest = "ANT-IN",
          kind = "capstone", tier = 1, prereqs = {}, cost = "",
          payoff = "", condition = "creed", unlocks = "Keystone fork, creed-picked: Temple Stores (the surplus is gathered and redistributed by command; famine-resistant, stable, and markets stay thin) vs Open Granaries (the surplus is priced and traded; markets deepen early, famine risk stays live). Exclusion: availability-window. The campaign's markets-not-command premise (HISTORY.md claim 1) made a ring-1 choice. Creed-picked for AI nations; BL-275's sweep can assert how often Open-Granaries worlds emerge.", status = "derived" },
        { id = "KS-SOVEREIGN", name = "Sovereign Doctrine", quest = "ANT-IN",
          kind = "capstone", tier = 4, prereqs = {}, cost = "",
          payoff = "", condition = "creed", unlocks = "Keystone fork, creed-picked: Chartered Capital (courts bind the sovereign; cheaper state credit, corporate autonomy, seizure carries a lasting credit cost) vs Command Estate (crown monopolies and confiscation rights; immediate revenue, chronic credit penalty, corps operate at the sovereign's pleasure). Exclusion: availability-window. HISTORY.md Stage 3 turned from narration into a choice; the sealed-oath god's provinces take Chartered Capital (the BL-218 pattern).", status = "derived" },
        { id = "KS-FUEL", name = "Fuel Doctrine", quest = "ANT-MA",
          kind = "capstone", tier = 4, prereqs = {}, cost = "",
          payoff = "", condition = "creed", unlocks = "Keystone fork, creed-picked: Coke (scale; wants coalfields) vs Charcoal (quality; wants forest). Exclusion: availability-window. A real historical fork: charcoal-iron nations held the quality niche while coke nations took the scale. Relocated from ring T5 by the industrial pass so the T4/T5 Materials vertex can require it taken — the fuel choice predates the industrial band.", status = "derived" },
        { id = "KS-LABOUR", name = "Labour Doctrine", quest = "ANT-AG",
          kind = "capstone", tier = 5, prereqs = {}, cost = "",
          payoff = "", condition = "creed", unlocks = "Keystone fork, creed-picked: Cleared Holdings (consolidate the land and release the labour fast: an urban workforce in a generation, at the cost of unrest and a hollowed countryside) vs Smallholder Tenure (the land stays divided: industrialisation starts late, the domestic market is deeper, rural demography survives the transition). Exclusion: availability-window. The human price of the divergence made into a choice. Direct input to BL-273 (province demography): growth rate, urban share, and the unrest the Nation AI inherits.", status = "derived" },
        { id = "KS-WORKS", name = "Works Doctrine", quest = "ANT-MA",
          kind = "capstone", tier = 5, prereqs = {}, cost = "",
          payoff = "", condition = "creed", unlocks = "Keystone fork, creed-picked: State Arsenal (the heavy plant is the sovereign's; capacity arrives fast and stays under command, and companies rent what they cannot own) vs Private Works (the heavy plant is chartered and owned; a slower start, compounding reinvestment, and corporations that own capacity outright). Exclusion: availability-window. Not a restatement of Sovereign Doctrine: that fork decides whether courts bind the sovereign, this one decides who owns the furnaces. Sets the terms a player corporation operates on in 1960; pairs with T5-IN-03 General Incorporation.", status = "derived" },
        -- ------------------------------------------------- E0-HEAVY (stub, 4)
        { id = "E0-HI-01", name = "Blast-Furnace Steel", quest = "E0-HEAVY",
          kind = "invention", prereqs = {}, cost = "M", payoff = "building",
          condition = "research", unlocks = "Steel Mill", status = "stub" },
        { id = "E0-HI-02", name = "Industrial Chemistry", quest = "E0-HEAVY",
          kind = "invention", prereqs = { "E0-HI-01" }, cost = "M", payoff = "recipe",
          condition = "research", unlocks = "Petroleum -> refined fuel chains", status = "stub" },
        { id = "E0-HI-03", name = "Blast-Furnace Steel II", quest = "E0-HEAVY",
          kind = "tier", tier = 2, prereqs = { "E0-HI-01" }, cost = "S", payoff = "efficiency",
          condition = "research", unlocks = "Steel yield up", status = "stub" },
        { id = "E0-HI-04", name = "Integrated Supply Chains", quest = "E0-HEAVY",
          kind = "capstone", prereqs = { "E0-HI-02" }, cost = "XL", payoff = "gate",
          condition = "surplus", unlocks = "Quest goal: sustained steel + fuel surplus feeds Rocketry", status = "stub" },

        -- -------------------------------------------------- E0-ELEC (stub, 4)
        { id = "E0-EC-01", name = "Semiconductor Fabrication", quest = "E0-ELEC",
          kind = "invention", prereqs = {}, cost = "M", payoff = "building",
          condition = "research", unlocks = "Semiconductor Fab", status = "stub" },
        { id = "E0-EC-02", name = "Compute Clusters", quest = "E0-ELEC",
          kind = "invention", prereqs = { "E0-EC-01" }, cost = "M", payoff = "recipe",
          condition = "research", unlocks = "Compute — the R&D Lab input good", status = "stub" },
        { id = "E0-EC-03", name = "Semiconductor Fabrication II", quest = "E0-ELEC",
          kind = "tier", tier = 2, prereqs = { "E0-EC-01" }, cost = "S", payoff = "efficiency",
          condition = "research", unlocks = "Fab yield up", status = "stub" },
        { id = "E0-EC-04", name = "Information Economy", quest = "E0-ELEC",
          kind = "capstone", prereqs = { "E0-EC-02" }, cost = "XL", payoff = "gate",
          condition = "market", unlocks = "Quest goal: compute cheap enough to industrialise research", status = "stub" },

        -- ---------------------------------------------------- L-MIL (BL-344, 1)
        -- THE ONE LIVE GATE. Every other node in this file is authored data the
        -- F9 viewer draws; this one is actually earnable and actually unlocks
        -- content (building_type::military_base, BL-325). Its PREDICATE is NOT
        -- authored here -- src/world/tech_gate.cpp owns it, because the gate has
        -- to be linkable from the Lua-free world superset that construction.cpp
        -- lives in, and one predicate in two files is one predicate too many.
        -- `condition` below stays the descriptive label it has always been.
        --
        -- Military rather than economic on purpose (BL-094's design test, quoted
        -- in BL-344): a technology that can only unlock a building is being
        -- designed for the corporate player the governing-body pivot is moving
        -- away from.
        { id = "E0-ML-01", name = "Standing Garrison Doctrine", short_name = "Garrison",
          quest = "L-MIL",
          kind = "invention", prereqs = {}, cost = "M", payoff = "building",
          condition = "structure", unlocks = "Military Base", status = "stub" },

        -- ------------------------------------------------ E0-ROCKET (stub, 5)
        { id = "E0-RK-01", name = "Guided Rocketry", quest = "E0-ROCKET",
          kind = "invention", prereqs = {}, cost = "M", payoff = "enabling",
          condition = "research", unlocks = "Rocket airframes and guidance", status = "stub" },
        { id = "E0-RK-02", name = "Orbital-Class Boosters", quest = "E0-ROCKET",
          kind = "invention", prereqs = { "E0-RK-01" }, cost = "L", payoff = "building",
          condition = "research", unlocks = "Launchpad", status = "stub" },
        { id = "E0-RK-03", name = "Cryogenic Ground Handling", quest = "E0-ROCKET",
          kind = "invention", prereqs = { "E0-RK-01" }, cost = "M", payoff = "recipe",
          condition = "research", unlocks = "Propellant production and storage on the pad", status = "stub" },
        { id = "E0-RK-04", name = "Orbital-Class Boosters II", quest = "E0-ROCKET",
          kind = "tier", tier = 2, prereqs = { "E0-RK-02" }, cost = "S", payoff = "efficiency",
          condition = "research", unlocks = "Payload per launch up", status = "stub" },
        { id = "E0-RK-05", name = "Operable Launch Complex", quest = "E0-ROCKET",
          kind = "capstone", prereqs = { "E0-RK-02", "E0-RK-03" }, cost = "XL", payoff = "gate",
          condition = "structure", unlocks = "Quest goal: staffed Launchpad + propellant stockpile; opens the five Era 1 sectors", status = "stub" },

        -- =====================================================================
        -- ERA 1 — five sectors, three rings, four deed-gated keystones.
        -- All "sketch" — first draft, unreviewed node list.
        -- =====================================================================

        -- ---------------------------------------------------------- Launch (6)
        { id = "E1-LA-01", name = "Expendable Lift Cadence", quest = "E1-LAUNCH",
          kind = "invention", tier = 1, prereqs = { "E0-RK-05" }, cost = "M", payoff = "efficiency",
          condition = "research", unlocks = "Launch cost per kg down; repeat dispatch without refit", status = "sketch" },
        { id = "E1-LA-02", name = "Recovery & Refurbishment", quest = "E1-LAUNCH",
          kind = "invention", tier = 1, prereqs = { "E0-RK-05" }, cost = "M", payoff = "efficiency",
          condition = "research", unlocks = "Launch cost falls with cadence", status = "sketch" },
        { id = "E1-LA-KEYSTONE", name = "Lift Doctrine — Ten Flights", short_name = "Lift Doctrine", quest = "E1-LAUNCH",
          kind = "capstone", tier = 2, prereqs = { "E1-LA-01", "E1-LA-02" }, cost = "L", payoff = "gate",
          condition = "deed", unlocks = "DEED: cumulative launches >= N from one body. Opens a permanent fork — Reusable Chemical (A) vs Fixed Infrastructure (B).", status = "sketch" },
        { id = "E1-LA-03A", name = "Reusable Booster (branch A)", short_name = "Reusable Booster", quest = "E1-LAUNCH",
          kind = "invention", tier = 2, prereqs = { "E1-LA-KEYSTONE" }, cost = "L", payoff = "efficiency",
          condition = "research", unlocks = "[Lift Doctrine A] Launchpad throughput up; low capital, scales anywhere. Excludes branch B.", status = "sketch" },
        { id = "E1-LA-03B", name = "Mass Driver (branch B)", short_name = "Mass Driver", quest = "E1-LAUNCH",
          kind = "invention", tier = 3, prereqs = { "E1-LA-KEYSTONE" }, cost = "XL", payoff = "building",
          condition = "research", unlocks = "[Lift Doctrine B] Non-rocket lift; enormous capital + a site requirement, then near-zero marginal lift. Excludes branch A.", status = "sketch" },
        { id = "E1-LA-04", name = "Heavy Lift Stack", quest = "E1-LAUNCH",
          kind = "invention", tier = 2, prereqs = { "E1-LA-KEYSTONE" }, cost = "L", payoff = "building",
          condition = "research", unlocks = "Oversize payload class (assembly modules)", status = "sketch" },
        { id = "E1-LA-05", name = "Launch Site Network", quest = "E1-LAUNCH",
          kind = "tier", tier = 3, prereqs = { "E1-LA-03A" }, cost = "L", payoff = "enabling",
          condition = "research", unlocks = "Dispatch from a second body; retires the single-site dispatch limit", status = "sketch" },

        -- -------------------------------------------------------- Volatiles (8)
        { id = "E1-VO-01", name = "Volatile Prospecting", quest = "E1-VOLATILES",
          kind = "invention", tier = 1, prereqs = { "E0-RK-05" }, cost = "M", payoff = "resource",
          condition = "research", unlocks = "Ice/water richness bands appear in survey", status = "sketch" },
        { id = "E1-VO-02", name = "Ice Extraction", quest = "E1-VOLATILES",
          kind = "invention", tier = 1, prereqs = { "E1-VO-01" }, cost = "M", payoff = "building",
          condition = "research", unlocks = "Ice Extractor", status = "sketch" },
        { id = "E1-VO-03", name = "Water Purification", quest = "E1-VOLATILES",
          kind = "invention", tier = 2, prereqs = { "E1-VO-02" }, cost = "M", payoff = "recipe",
          condition = "research", unlocks = "Water recipe chain", status = "sketch" },
        { id = "E1-VO-KEYSTONE", name = "Propellant Doctrine — The First Tank", short_name = "Propellant Doctrine", quest = "E1-VOLATILES",
          kind = "capstone", tier = 2, prereqs = { "E1-VO-03" }, cost = "L", payoff = "gate",
          condition = "deed", unlocks = "DEED: produce any propellant off-world, once. Opens a permanent fork — Methalox (A) vs Hydrolox (B), read from the body's substrate.", status = "sketch" },
        { id = "E1-VO-04A", name = "Sabatier Reactor (branch A, Methalox)", short_name = "Sabatier Reactor", quest = "E1-VOLATILES",
          kind = "invention", tier = 2, prereqs = { "E1-VO-KEYSTONE" }, cost = "M", payoff = "recipe",
          condition = "research", unlocks = "[Propellant Doctrine A] CO2 + H2 -> methane; wants a carbon source (the methane tell). Excludes branch B.", status = "sketch" },
        { id = "E1-VO-04B", name = "Electrolysis (branch B, Hydrolox)", short_name = "Electrolysis", quest = "E1-VOLATILES",
          kind = "invention", tier = 2, prereqs = { "E1-VO-KEYSTONE" }, cost = "M", payoff = "recipe",
          condition = "research", unlocks = "[Propellant Doctrine B] Water -> LH2 + LOX; wants water ice, higher performance, harder storage. Excludes branch A.", status = "sketch" },
        { id = "E1-VO-05", name = "Cryogenic Storage", quest = "E1-VOLATILES",
          kind = "invention", tier = 2, prereqs = { "E1-VO-04A", "E1-VO-04B" }, cost = "M", payoff = "building",
          condition = "research", unlocks = "Depot tank; sets the boil-off baseline", status = "sketch" },
        { id = "E1-VO-06", name = "In-Situ Tank Fabrication", quest = "E1-VOLATILES",
          kind = "tier", tier = 3, prereqs = { "E1-VO-05" }, cost = "M", payoff = "access",
          condition = "research", unlocks = "Depot buildable without lifted parts", status = "sketch" },
        { id = "E1-VO-07", name = "Propellant Export", quest = "E1-VOLATILES",
          kind = "tier", tier = 3, prereqs = { "E1-VO-05" }, cost = "M", payoff = "resource",
          condition = "market", unlocks = "Propellant enters the space market as a traded good", status = "sketch" },

        -- --------------------------------------------------------- Mobility (5, no keystone)
        { id = "E1-MO-01", name = "Transfer Planning", quest = "E1-MOBILITY",
          kind = "invention", tier = 1, prereqs = { "E0-RK-05" }, cost = "S", payoff = "efficiency",
          condition = "research", unlocks = "Propellant per leg down", status = "sketch" },
        { id = "E1-MO-02", name = "High-Impulse Engines", quest = "E1-MOBILITY",
          kind = "invention", tier = 2, prereqs = { "E1-MO-01" }, cost = "L", payoff = "efficiency",
          condition = "research", unlocks = "Propellant tax down; longer legs reachable", status = "sketch" },
        { id = "E1-MO-03", name = "Electric Propulsion", quest = "E1-MOBILITY",
          kind = "invention", tier = 2, prereqs = { "E1-MO-01" }, cost = "L", payoff = "efficiency",
          condition = "research", unlocks = "Propellant tax down for slow cargo; unlocks a bulk-freight lane class", status = "sketch" },
        { id = "E1-MO-04", name = "Nuclear Thermal", quest = "E1-MOBILITY",
          kind = "tier", tier = 3, prereqs = { "E1-MO-02" }, cost = "XL", payoff = "efficiency",
          condition = "research", unlocks = "Reaches the outer-body lanes; transit time down", status = "sketch" },
        { id = "E1-MO-05", name = "Depot Routing", quest = "E1-MOBILITY",
          kind = "tier", tier = 3, prereqs = { "E1-MO-03" }, cost = "M", payoff = "enabling",
          condition = "research", unlocks = "Refuel mid-route; lane freshness intel", status = "sketch" },

        -- ------------------------------------------------------------ Yards (6)
        { id = "E1-YA-01", name = "Orbital Rendezvous", quest = "E1-YARDS",
          kind = "invention", tier = 1, prereqs = { "E0-RK-05" }, cost = "M", payoff = "enabling",
          condition = "research", unlocks = "Two-vehicle operations", status = "sketch" },
        { id = "E1-YA-02", name = "Modular Assembly", quest = "E1-YARDS",
          kind = "invention", tier = 2, prereqs = { "E1-YA-01" }, cost = "L", payoff = "building",
          condition = "research", unlocks = "Assembly Plant", status = "sketch" },
        { id = "E1-YA-KEYSTONE", name = "Yard Doctrine — The First Truss", short_name = "Yard Doctrine", quest = "E1-YARDS",
          kind = "capstone", tier = 2, prereqs = { "E1-YA-02" }, cost = "L", payoff = "gate",
          condition = "deed", unlocks = "DEED: complete one structure assembled off Earth. Opens a permanent fork — Orbital Assembly (A) vs Surface Assembly (B).", status = "sketch" },
        { id = "E1-YA-03A", name = "Orbital Port (branch A, Orbital Assembly)", short_name = "Orbital Port", quest = "E1-YARDS",
          kind = "invention", tier = 2, prereqs = { "E1-YA-KEYSTONE" }, cost = "L", payoff = "building",
          condition = "research", unlocks = "[Yard Doctrine A] Orbital Port; joins the trade graph; no gravity well but total dependence on lift. Excludes branch B.", status = "sketch" },
        { id = "E1-YA-03B", name = "Surface Assembly Yard (branch B)", short_name = "Surface Assembly", quest = "E1-YARDS",
          kind = "invention", tier = 2, prereqs = { "E1-YA-KEYSTONE" }, cost = "L", payoff = "building",
          condition = "research", unlocks = "[Yard Doctrine B] Build on the body; local materials, but pays the well every launch. Excludes branch A.", status = "sketch" },
        { id = "E1-YA-04", name = "Station Fabrication", quest = "E1-YARDS",
          kind = "tier", tier = 3, prereqs = { "E1-YA-03A" }, cost = "L", payoff = "access",
          condition = "research", unlocks = "Habitat/station class; orbital build sites", status = "sketch" },
        { id = "E1-YA-05", name = "On-Orbit Servicing", quest = "E1-YARDS",
          kind = "tier", tier = 3, prereqs = { "E1-YA-03A", "E1-YA-03B" }, cost = "M", payoff = "efficiency",
          condition = "research", unlocks = "Asset maintenance down; retires single-use orbital assets", status = "sketch" },

        -- ------------------------------------------------------- Extraction (5)
        { id = "E1-EX-01", name = "Regolith Excavation", quest = "E1-EXTRACTION",
          kind = "invention", tier = 1, prereqs = { "E0-RK-05" }, cost = "M", payoff = "building",
          condition = "research", unlocks = "Surface Extractor", status = "sketch" },
        { id = "E1-EX-02", name = "Metallic Body Working", quest = "E1-EXTRACTION",
          kind = "invention", tier = 2, prereqs = { "E1-EX-01" }, cost = "M", payoff = "recipe",
          condition = "research", unlocks = "Iron-nickel ore chain; access to metallic bodies", status = "sketch" },
        { id = "E1-EX-03", name = "Platinum-Group Separation", quest = "E1-EXTRACTION",
          kind = "invention", tier = 2, prereqs = { "E1-EX-02" }, cost = "L", payoff = "recipe",
          condition = "research", unlocks = "PGM recipe; PGM enters the traded-goods list", status = "sketch" },
        { id = "E1-EX-04", name = "Deep Regolith Processing", quest = "E1-EXTRACTION",
          kind = "tier", tier = 3, prereqs = { "E1-EX-01" }, cost = "M", payoff = "efficiency",
          condition = "research", unlocks = "Extractor throughput up", status = "sketch" },
        { id = "E1-EX-KEYSTONE", name = "Autonomy Doctrine — The Empty Shift", short_name = "Autonomy Doctrine", quest = "E1-EXTRACTION",
          kind = "capstone", tier = 3, prereqs = { "E1-EX-04", "L-AU-01" }, cost = "L", payoff = "gate",
          condition = "deed", unlocks = "DEED: run an off-world building at zero workforce for N days. Crosses Extraction x L-AUTO. Opens a permanent fork — Crewed Operations (A) vs Autonomous Fleets (B).", status = "sketch" },
        { id = "E1-EX-05A", name = "Crewed Operations (branch A)", short_name = "Crewed Operations", quest = "E1-EXTRACTION",
          kind = "invention", tier = 3, prereqs = { "E1-EX-KEYSTONE" }, cost = "L", payoff = "efficiency",
          condition = "research", unlocks = "[Autonomy Doctrine A] Higher output ceiling; habitability and life-support burden. Excludes branch B.", status = "sketch" },
        { id = "E1-EX-05B", name = "Autonomous Mining Rig (branch B)", short_name = "Autonomous Rig", quest = "E1-EXTRACTION",
          kind = "invention", tier = 3, prereqs = { "E1-EX-KEYSTONE" }, cost = "L", payoff = "efficiency",
          condition = "research", unlocks = "[Autonomy Doctrine B] Workforce scalar collapses; electronics dependency becomes strategic. Excludes branch A.", status = "sketch" },

        -- --------------------------------------------------------- L-LOG (stub, 4)
        { id = "L-LG-01", name = "Freight Optimisation", quest = "L-LOG",
          kind = "invention", prereqs = {}, cost = "M", payoff = "efficiency",
          condition = "research", unlocks = "Convoy cost per leg down", status = "stub" },
        { id = "L-LG-02", name = "Ion Propulsion", quest = "L-LOG",
          kind = "invention", prereqs = { "L-LG-01" }, cost = "L", payoff = "efficiency",
          condition = "research", unlocks = "Propellant per space leg down; slower transit", status = "stub" },
        { id = "L-LG-03", name = "Ion Propulsion II", quest = "L-LOG",
          kind = "tier", tier = 2, prereqs = { "L-LG-02" }, cost = "M", payoff = "efficiency",
          condition = "research", unlocks = "Thrust up (mid-tier must carry a real trade-off — the TI lesson)", status = "stub" },
        { id = "L-LG-04", name = "Nuclear-Thermal Propulsion", quest = "L-LOG",
          kind = "invention", prereqs = { "L-LG-02" }, cost = "XL", payoff = "efficiency",
          condition = "research", unlocks = "High-thrust deep-space transit", status = "parked" },

        -- -------------------------------------------------- L-AUTO (stub, 3)
        { id = "L-AU-01", name = "Industrial Automation", quest = "L-AUTO",
          kind = "invention", prereqs = {}, cost = "M", payoff = "efficiency",
          condition = "research", unlocks = "Workforce scalar down across extraction", status = "stub" },
        { id = "L-AU-02", name = "Industrial Automation II", quest = "L-AUTO",
          kind = "tier", tier = 2, prereqs = { "L-AU-01" }, cost = "S", payoff = "efficiency",
          condition = "research", unlocks = "Workforce scalar down further", status = "stub" },
        { id = "L-AU-03", name = "Autonomous Operations", quest = "L-AUTO",
          kind = "invention", prereqs = { "L-AU-01" }, cost = "L", payoff = "efficiency",
          condition = "research", unlocks = "Remote/unmanned building operation off-world", status = "stub" },
    },
}
